# Generated by Django 4.1.4 on 2022-12-23 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_alter_pdf_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdf',
            options={'get_latest_by': ['id']},
        ),
        migrations.AlterField(
            model_name='pdf',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.pdf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['id'],
            },
        ),
    ]
